qcd: Correct `undent` and `brew audit` errors
Remove `undent` call, which apparently is no longer implemented
according to this error message:

    Error: undefined method `undent' for #<String:0x000000014fd17590>
    Did you mean?  undef
                   indent
                   indent!
    /opt/homebrew/Library/Taps/teddywing/homebrew-formulae/HomebrewFormula/qcd.rb:16:in `caveats'
    /opt/homebrew/Library/Homebrew/caveats.rb:23:in `caveats'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:224:in `empty?'
    /opt/homebrew/Library/Homebrew/formula_installer.rb:777:in `caveats'
    /opt/homebrew/Library/Homebrew/formula_installer.rb:836:in `finish'
    /opt/homebrew/Library/Homebrew/upgrade.rb:209:in `install_formula'
    /opt/homebrew/Library/Homebrew/install.rb:327:in `install_formula'
    /opt/homebrew/Library/Homebrew/install.rb:317:in `block in install_formulae'
    /opt/homebrew/Library/Homebrew/install.rb:316:in `each'
    /opt/homebrew/Library/Homebrew/install.rb:316:in `install_formulae'
    /opt/homebrew/Library/Homebrew/cmd/install.rb:222:in `install'
    /opt/homebrew/Library/Homebrew/brew.rb:93:in `<main>'

Also correct the following `brew audit` warnings:

    16: col 16: Place the first line of a multi-line method definition's body on its own line.
    25: col 1: `EOS` is not aligned with `def caveats; <<-EOS.undent`.